apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  echoedList: 
{{ toYaml .Values.TestList | indent 4 }}
  echoedListRange:
    {{ range .Values.TestList }}
    - {{ . }}
    {{ end }}
  firstItem: 
    # Or index .Values.TestList 0
    {{- $first := first .Values.TestList -}}
    {{- if ne $first nil }}
    {{ $first }}
    {{- else }}
    Not Found
    {{- end }}
  thirdItem: 
    {{- if gt (len .Values.TestList) 2 }}
      {{ index .Values.TestList 2 }}
    {{ else }}
      Not Found
    {{ end }}
  uniqueList:
{{ uniq .Values.TestList | toYaml  | indent 4 }}
  uniqueListLength: {{ uniq .Values.TestList | len }} 
  withoutHelm: 
{{ without .Values.TestList "helm" | toYaml | indent 4 }}
  sliceOneToThree:
{{ if lt (len .Values.TestList) 3 }}
    []
{{ else }}
{{ slice .Values.TestList 1 3 | toYaml | indent 4 }}
{{ end }}
  goFirst:
{{ prepend .Values.TestList "go" | toYaml | indent 4 }}
  httpLast:
{{ append .Values.TestList "http" | toYaml | indent 4 }}
  doubledList:
{{ concat .Values.TestList .Values.TestList | toYaml | indent 4 }}
