version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    ports: 
      - "8081:8081"
    environment:
      - AUTH_ADDRESS: auth
      - AUTH_SERVICE_SERVICE_HOST: auth # in orde to make docker see a kubernetes generated variable
  tasks:
    build: ./tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
    volumes:
      - /app/tasks
