apiVersion: v1
kind: ConfigMap
metadata:
  name: base64-example
data:
{{- $baseString := "test string" }}
  encodedBase64:
    {{ b64enc $baseString }} 
  decodedBase64:
    {{ b64enc $baseString | b64dec }} 
  encodedBase32:
    {{ b32enc $baseString }} 
  decodedBase32:
    {{ b32enc $baseString | b32dec }} 


