apiVersion: v1
kind: ConfigMap
metadata:
  name: passwords-example
data:
  derivedPassword: |
    # TODO Probably take these from values or .Files.Get
    # This is a "master password" 
    # https://spectre.app/spectre-algorithm.pdf
    {{ derivePassword 3 "long" "password" "user" "example.com" }}
  htpasswd: |
    # For basic auth using Apache
    {{ htpasswd "username" "password" }}
  bcryptExample: |
    # Perform bcrypt algorithm
    {{ bcrypt "password" }} 
