apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # this does not expose the IP to the outside world but only from inside the cluster, 
  # while LoadBalancer does expose the IP to the outside world
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
