version: '3.8'

services:
  server:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/dockerfiles/nginx.dockerfile
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/${APP_NAME}
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/conf/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf:ro  
    depends_on:
      - php
  mysql:
      container_name: mysql
      image: mysql:8.4
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"
  php:
    container_name: backend
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
      args:
        APP_NAME: ${APP_NAME}
    volumes:
      - ./src:/var/www/${APP_NAME}:delegated
    depends_on:
      - mysql

volumes:
  mysql-data: